### PR TITLE
Add github urls to setup.py

### PR DESCRIPTION
**Pull request by haakenlid**
This will add relevant links in the PyPI page sidebar.

### CODE REVIEW

**Comment by Starou** [comment]
Thanks @haakenlid, could you please bump the version to 1.0.2 and rebase before I merge?

**Comment by haakenlid** [comment]
Can I rebase the existing pull request? You mean like this? https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

**Comment by Starou** [comment]
Sorry, I meant squashing the (3) commits into a single one. And then `git push --force` your branch.

**Comment by haakenlid** [comment]
Ok. So you can't squash when merging the pull request?

**Comment by Starou** [comment]
I have never noticed that it is possible to squash commits here! I prefer the squashing operation done by the author of the PR but I'll make an exception here because it is a trivial one.

**Pull request merged**
