### PR TITLE
Support Python 3.4+

### PR DESCRIPTION
**Pull request by andreif**
I haven't tested it on Windows.

### CODE REVIEW

**Comment by andreif** [comment]
Fixes got merged in cackharot/suds-py3#12 so I will change to the main `suds-py3` package for Python 3.4+

**Comment by Starou** [comment]
Hi @andreif and thanks for your efforts!
I'll try to review your PR this month (lot of work atm).

**Comment by mnvx** [comment]
Hello. I'm very interested in SimpleIDML for Python3. What plans for this merge?

**Comment by Starou** [comment]
Hi @mnvx, 
To be honest, there is no plan because my experience in migrating code to Python3 is very limited and the projects using the lib are still in Python2.
I can't just trust the test suite on this one, there must be some real-word testing.

**Comment by mnvx** [comment]
@Starou, thanks for response. Currently I use py3 branch of @andreif project. What about new branch for python 3 in Starou/SimpleIDML project and merging this pull request into that branch?

**Comment by Starou** [comment]
Ok, I just created a python3-support branch, rebased @andreif branch against it and opened a PR. But the tests failed :

https://travis-ci.org/Starou/SimpleIDML/builds/289403849

**Comment by mnvx** [comment]
Branch python3-support currently points to master. Do I must use branch andreif-py3?

**Comment by Starou** [comment]
I'd like the test suite to succeed before merging the PR into python3-support branch. The rebasing must have break some stuff.

**Comment by mnvx** [comment]
May you help me to understand next error please?

I try to use execute `print(package.xml_structure)` but I stuck with error at this line: https://github.com/mnvx/SimpleIDML/blob/py3/src/simple_idml/idml.py#L88

```
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    manager.run()
  File "/var/www/gost/gost/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/var/www/gost/gost/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/var/www/gost/gost/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/var/www/gost/gost/schema/commands/convert.py", line 23, in run
    result = converter.convert(filename=input_filename).decode('utf-8')
  File "/var/www/gost/gost/schema/service/converter/gost_r_converter.py", line 25, in convert
    print(package.xml_structure)
  File "/var/www/gost/SimpleIDML/src/simple_idml/idml.py", line 112, in xml_structure
    append_childs(source_node, structure)
  File "/var/www/gost/SimpleIDML/src/simple_idml/idml.py", line 88, in append_childs
    for elt in source_node.iterchildren():
  File "src/lxml/etree.pyx", line 1445, in lxml.etree._Element.iterchildren (src/lxml/etree.c:59428)
TypeError: <schema.commands.convert.Convert object at 0x7f9bd033eac8>: Argument 'node' has incorrect type (expected lxml.etree._Element, got XMLElement)
```

**Comment by Starou** [comment]
Check your lxml version. This should be handled correctly in setup.py:

https://github.com/Starou/SimpleIDML/commit/ec2210e22e40c5a113239652e46f48067dbe859b#diff-2eeaed663bd0d25b7e608891384b7298

There are some backward incompatibilities in the last version(s) I hadn't had time to address.

**Comment by mnvx** [comment]
@Starou, thanks! Now `print(package.xml_structure) ` works, but result seems not correct. It outputs only next one tag for my large IDML file:

```xml
<Root Self="di2"/>
```

**Comment by Starou** [comment]
Does your IDML file has any Structure? (Views > Structure > Show Structure)

**Comment by Starou** [comment]
See PR#40

**Pull request closed without merging**
